### ISSUE TITLE
fail to reproduce the repo and stuck at step 4(f2fs mounting failure)

### ISSUE THREAD

**Issue by 108062138** [pingxiang-chen/bpf-f2fs-zonetrace#6]
As title, I follow the `README.md` in `bpt-f2fs-zonetrace` repo, directly utilize `debian.qcow2` in femu, and emulate a 4 GB ZNS.
But things go wrong when I attempt to issue command `sudo ./scripts/mount_f2fs.sh` in step4. The error message states that loop77 is too small. I solve the problem by manually change `/tmp/f2fs_metadata.img`'s file size from 256M to 1024M

I suggest that we should make the `256M` in `truncate -s 256M $METADATA_IMG` inside `mount_f2fs.sh` a varaible to avoid manually editing the script

|env.|modify part|
|--|--|
|![image](https://github.com/user-attachments/assets/3ca7d893-55db-412e-91b5-b5c5ea7bd961)|![image](https://github.com/user-attachments/assets/765d34fe-d11d-420f-af77-8c13a707d5af)|

**Comment by pingxiang-chen** [comment]
1024M is able to be used in our system. However, thanks for pointing this out.
